import { test, expect } from '@playwright/test';
import { loginInPage, loginAsAdmin, protocolHeaders, FIXTURE_URLS, TEST_ACCOUNT } from './support';
test('列表偏好、独立频道名称、批量创建及加密备份入口', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  await page.request.put('/api/settings', { headers, data: { feedView: 'list' } });
  await page.request.post('/api/feeds', { headers, data: { name: 'Management fixture', url: FIXTURE_URLS.static, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  await page.goto('/');
  await expect(page.getByRole('button', { name: '列表', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '卡片', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: '卡片', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const view = page.getByRole('button', { name: /^查看订阅 / }).first();
  await view.click();
  const dialog = page.getByRole('dialog');
  const rss = await dialog.locator('input[readonly]').inputValue();
  await dialog.getByText('订阅设置', { exact: true }).click();
  await dialog.getByLabel('阅读器中的订阅名称').fill('阅读器专用名称 & v2');
  await dialog.getByRole('button', { name: '保存订阅名称' }).click();
  await expect(page.getByRole('status')).toContainText('订阅名称已保存');
  await expect((await page.request.get(rss)).text()).resolves.toContain('阅读器专用名称 &amp; v2');
  await dialog.getByRole('button', { name: '关闭' }).click();
  await page.getByRole('button', { name: '批量添加', exact: true }).click();
  await page.getByLabel('每行一个网址（最多 100 个）').fill(`${FIXTURE_URLS.static}?batch=v2\n${FIXTURE_URLS.ambiguous}?batch=v2`);
  await page.getByRole('button', { name: '开始批量识别' }).click();
  await expect(page.getByText(/已创建/).first()).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('button', { name: '打开并调整匹配' }).first()).toBeVisible();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('button', { name: '完整备份', exact: true }).click();
  const panel = page.locator('section').filter({ has: page.getByRole('heading', { name: '备份与迁移' }) });
  await panel.getByLabel('当前管理员密码').fill(TEST_ACCOUNT.password);
  await panel.getByLabel('备份密码（至少 12 个字符）').fill('test-backup-passphrase');
  const download = page.waitForEvent('download');
  await panel.getByRole('button', { name: '下载导出文件' }).click();
  expect((await download).suggestedFilename()).toMatch(/^feedlantern-backup/);
});

test('移动端列表、选择后复制和过滤清空选择', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  await page.request.put('/api/settings', { headers, data: { feedView: 'list' } });
  const created = await page.request.post('/api/feeds', { headers, data: { name: '移动端独立测试', url: FIXTURE_URLS.static, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  expect(created.ok()).toBeTruthy();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('搜索订阅').fill('移动端独立测试');
  await page.getByLabel('选择订阅 移动端独立测试').check();
  await expect(page.getByText('已选择 1 项')).toBeVisible();
  await page.getByRole('button', { name: '复制 RSS 地址', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('已复制 1 项');
  await page.getByLabel('选择订阅 移动端独立测试').check();
  await page.getByLabel('搜索订阅').fill('不匹配任何订阅');
  await expect(page.getByText('已选择 1 项')).toHaveCount(0);
  await page.getByLabel('搜索订阅').fill('移动端独立测试');
  await expect(page.getByLabel('选择订阅 移动端独立测试')).not.toBeChecked();
  const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }));
  expect(width.scroll).toBeLessThanOrEqual(width.viewport);
  await page.screenshot({ path: 'test-results/mobile-management.png', fullPage: true });
});
