import { test, expect } from './fixtures';
import { loginInPage, loginAsAdmin, protocolHeaders, FIXTURE_URLS, TEST_ACCOUNT } from './support';
test('列表偏好、统一订阅名称、批量创建及加密备份入口', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  await page.request.put('/api/settings', { headers, data: { feedView: 'list' } });
  await page.request.post('/api/feeds', { headers, data: { name: 'Management fixture', url: FIXTURE_URLS.static, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  await page.goto('/');
  await expect(page.getByRole('button', { name: '列表', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '卡片', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: '卡片', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const view = page.getByRole('button', { name: /^查看订阅 / }).first();
  await view.click();
  const dialog = page.getByRole('dialog');
  const rss = await dialog.locator('input[readonly]').inputValue();
  await dialog.getByRole('button', { name: '订阅设置', exact: true }).click();
  await dialog.getByLabel('订阅名称').fill('阅读器专用名称 & v2');
  await dialog.getByRole('button', { name: '保存设置' }).click();
  await expect(page.getByRole('status')).toContainText('订阅设置已保存');
  await expect((await page.request.get(rss)).text()).resolves.toContain('阅读器专用名称 &amp; v2');
  await dialog.getByRole('button', { name: '关闭' }).click();
  await expect(page.getByRole('button', { name: '查看订阅 阅读器专用名称 & v2', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '批量添加', exact: true }).click();
  await page.getByLabel('每行一个网址（最多 100 个）').fill(`${FIXTURE_URLS.static}?batch=v2\n${FIXTURE_URLS.ambiguous}?batch=v2`);
  await page.getByRole('button', { name: '开始批量识别' }).click();
  await expect(page.getByText(/已创建/).first()).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('button', { name: '打开并调整匹配' }).first()).toBeVisible();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('button', { name: '完整备份', exact: true }).click();
  const panel = page.locator('section').filter({ has: page.getByRole('heading', { name: '备份与迁移' }) });
  await panel.getByLabel('当前管理员密码').fill(TEST_ACCOUNT.password);
  await panel.getByLabel('备份密码（至少 12 个字符）').fill('test-backup-passphrase');
  const download = page.waitForEvent('download');
  await panel.getByRole('button', { name: '下载导出文件' }).click();
  expect((await download).suggestedFilename()).toMatch(/^feedlantern-backup/);
});

test('移动端列表、选择后复制和过滤清空选择', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  await page.request.put('/api/settings', { headers, data: { feedView: 'list' } });
  const created = await page.request.post('/api/feeds', { headers, data: { name: '移动端独立测试', url: FIXTURE_URLS.static, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  expect(created.ok()).toBeTruthy();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('搜索订阅').fill('移动端独立测试');
  await page.getByLabel('选择订阅 移动端独立测试').check();
  await expect(page.getByText('已选择 1 项')).toBeVisible();
  await page.getByRole('button', { name: '复制 RSS 地址', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('已复制 1 项');
  await page.getByLabel('选择订阅 移动端独立测试').check();
  await page.getByLabel('搜索订阅').fill('不匹配任何订阅');
  await expect(page.getByText('已选择 1 项')).toHaveCount(0);
  await page.getByLabel('搜索订阅').fill('移动端独立测试');
  await expect(page.getByLabel('选择订阅 移动端独立测试')).not.toBeChecked();
  const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }));
  expect(width.scroll).toBeLessThanOrEqual(width.viewport);
  await page.screenshot({ path: 'test-results/mobile-management.png', fullPage: true });
});

test('独立设置入口、刷新间隔持久化、未保存提醒及操作保留输入', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  const created = await page.request.post('/api/feeds', { headers, data: { name: '刷新设置测试', url: FIXTURE_URLS.static, intervalMinutes: 60, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  const { feed, feedUrl } = await created.json();
  await page.goto('/');
  await page.getByLabel('搜索订阅').fill(feed.name);
  await page.getByRole('button', { name: `查看订阅 ${feed.name}`, exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText('Fixture article one')).toBeVisible();
  await expect(dialog.getByLabel('刷新间隔（分钟）')).toHaveCount(0);
  await expect(dialog.getByRole('button', { name: '轮换订阅密钥' })).toHaveCount(0);
  await dialog.getByRole('button', { name: '订阅设置', exact: true }).click();
  const interval = dialog.getByLabel('刷新间隔（分钟）');
  await expect(interval).toHaveValue('60');
  await expect(dialog.getByText('Fixture article one')).toHaveCount(0);
  await interval.fill('15');
  page.once('dialog', d => d.dismiss());
  await page.keyboard.press('Escape');
  await expect(interval).toHaveValue('15');
  await dialog.getByRole('button', { name: '暂停订阅' }).click();
  await expect(dialog.getByRole('button', { name: '恢复订阅' })).toBeEnabled();
  await expect(interval).toHaveValue('15');
  page.once('dialog', d => d.accept());
  await dialog.getByRole('button', { name: '轮换订阅密钥' }).click();
  await expect(dialog.locator('input[readonly]')).not.toHaveValue(feedUrl);
  await expect(interval).toHaveValue('15');
  await expect(dialog.getByRole('button', { name: '保存设置' })).toBeEnabled();
  await dialog.getByRole('button', { name: '保存设置' }).click();
  await expect(page.getByRole('status')).toContainText('订阅设置已保存');
  await expect(dialog.getByText('已暂停自动刷新')).toBeVisible();
  await dialog.getByRole('button', { name: '关闭' }).click();
  await expect(page.getByText('每 15 分钟', { exact: false })).toBeVisible();
  await page.reload();
  await page.getByLabel('搜索订阅').fill(feed.name);
  for (const view of ['列表', '卡片']) {
    await page.getByRole('button', { name: view, exact: true }).click();
    await page.getByRole('button', { name: `订阅设置 ${feed.name}`, exact: true }).click();
    await expect(interval).toHaveValue('15');
    await dialog.getByRole('button', { name: '关闭' }).click();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: `订阅设置 ${feed.name}`, exact: true }).click();
  await expect(interval).toBeVisible();
  const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }));
  expect(width.scroll).toBeLessThanOrEqual(width.viewport);
  await page.screenshot({ path: 'test-results/mobile-feed-settings.png', fullPage: true });
});

test('设置保存失败保留输入，规则编辑取消和保存返回设置', async ({ page }, testInfo) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  const created = await page.request.post('/api/feeds', { headers, data: { name: `规则设置返回测试-${testInfo.retry}`,  url: FIXTURE_URLS.static, rules: { item: '.article-card', title: '.article-title', link: 'a.article-link' } } });
  const { feed } = await created.json();
  await page.goto('/');
  await page.getByLabel('搜索订阅').fill(feed.name);
  await page.getByRole('button', { name: `订阅设置 ${feed.name}`, exact: true }).click();
  const dialog = page.getByRole('dialog');
  const interval = dialog.getByLabel('刷新间隔（分钟）');
  await interval.fill('30');
  await page.route(`**/api/feeds/${feed.id}`, route => route.request().method() === 'PATCH'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '测试保存失败' }) }) : route.continue());
  await dialog.getByRole('button', { name: '保存设置' }).click();
  await expect(dialog.getByRole('alert')).toContainText('测试保存失败');
  await expect(interval).toHaveValue('30');
  await page.unroute(`**/api/feeds/${feed.id}`);
  page.once('dialog', d => d.dismiss());
  await dialog.getByRole('button', { name: '编辑匹配规则' }).click();
  await expect(interval).toHaveValue('30');
  page.once('dialog', d => d.accept());
  await dialog.getByRole('button', { name: '编辑匹配规则' }).click();
  await expect(page.getByRole('heading', { name: '编辑匹配规则' })).toBeVisible();
  await page.getByRole('button', { name: '返回订阅' }).click();
  await expect(interval).toHaveValue('60');
  await dialog.getByRole('button', { name: '编辑匹配规则' }).click();
  await page.getByRole('button', { name: '打开并自动识别' }).click();
  await expect(page.getByText('Fixture article one').first()).toBeVisible({ timeout: 45000 });
  await page.getByRole('button', { name: '保存订阅', exact: true }).click();
  await expect(dialog).toHaveAttribute('aria-label', '订阅设置');
  await expect(interval).toHaveValue('60');
});

test('源网页不可用也能在设置中修改间隔，无需连接或预览', async ({ page }) => {
  const auth = await loginAsAdmin(page.request);
  const headers = protocolHeaders(auth.csrfToken);
  const created = await page.request.post('/api/feeds', { headers, data: { name: '离线来源设置测试', url: new URL('/unavailable', FIXTURE_URLS.static).href, rules: { item: 'article', title: 'h2', link: 'a' } } });
  expect(created.ok()).toBeTruthy();
  const { feed, feedUrl } = await created.json();
  expect(feed.lastError).toBeTruthy();
  await page.goto('/');
  await page.getByLabel('搜索订阅').fill(feed.name);
  await page.getByRole('button', { name: `订阅设置 ${feed.name}`, exact: true }).click();
  const dialog = page.getByRole('dialog');
  const browserRequests: string[] = [];
  page.on('request', request => { if (request.url().includes('/api/browser') || request.method() === 'PUT') browserRequests.push(request.url()); });
  await dialog.getByLabel('刷新间隔（分钟）').fill('120');
  await dialog.getByRole('button', { name: '保存设置' }).click();
  await expect(page.getByRole('status')).toContainText('订阅设置已保存');
  await expect(dialog.getByText('每 120 分钟刷新')).toBeVisible();
  await expect(dialog.locator('input[readonly]')).toHaveValue(feedUrl);
  expect(browserRequests).toEqual([]);
  const after = await (await page.request.get(`/api/feeds/${feed.id}`)).json();
  expect(after.feed.lastFetchedAt).toBe(feed.lastFetchedAt);
  expect(after.feed.lastError).toBe(feed.lastError);
  await page.screenshot({ path: 'test-results/desktop-feed-settings.png', fullPage: true });
});
